[versions]
jme = "3.8.0-stable"

[libraries]
jme3-core = {module="org.jmonkeyengine:jme3-core", version.ref = "jme"}
jme3-desktop = {module="org.jmonkeyengine:jme3-desktop", version.ref = "jme"}
jme3-lwjgl3 = {module="org.jmonkeyengine:jme3-lwjgl3", version.ref = "jme"}
jme3-android = {module="org.jmonkeyengine:jme3-android", version.ref = "jme"}